#!/usr/bin/env python3
"""Emit coop-offsets.json from the compiled offsets probe.

The harness reads the co-op save record out of emulated memory and needs the
real offset of coopPlayer2 inside SaveBlock1. Deriving that on the JS side means
restating the struct layout there, which drifts: sizeof(struct CoopPlayer2) is
632 rather than the 636 its fields sum to, so a harness computing "block size
minus record size" lands four bytes early and reads plausible nonsense.

src/coop_offsets_probe.c asks the compiler instead. The array is unreferenced
and --gc-sections drops it from the ROM, so this costs nothing at runtime; the
values are read back out of the object file.

    make modern
    python3 tools/coop/emit_offsets.py coop/harness/coop-offsets.json
"""

import json
import struct
import subprocess
import sys
from pathlib import Path

OBJ = Path("build/emerald/src/coop_offsets_probe.o")

FIELDS = [
    "sizeofSaveBlock1",
    "sizeofCoopPlayer2",
    "coopPlayer2",
    "playerName",
    "playerGender",
    "partyCount",
    "claimed",
    "pos",
    "location",
    "party",
]


def main(argv):
    out = Path(argv[1]) if len(argv) > 1 else Path("coop/harness/coop-offsets.json")

    if not OBJ.exists():
        print(f"error: {OBJ} not found. Run `make modern` first.", file=sys.stderr)
        return 1

    raw = subprocess.run(
        ["arm-none-eabi-objcopy", "-O", "binary", "--only-section=.rodata",
         str(OBJ), "/dev/stdout"],
        capture_output=True,
    ).stdout

    need = len(FIELDS) * 4
    if len(raw) < need:
        print(
            f"error: probe .rodata is {len(raw)} bytes, expected at least {need}.\n"
            "Did src/coop_offsets_probe.c change without this script being updated?",
            file=sys.stderr,
        )
        return 1

    values = struct.unpack(f"<{len(FIELDS)}I", raw[:need])
    data = dict(zip(FIELDS, values))

    # A sanity check the harness cannot do for itself: the record must sit
    # wholly inside the block it claims to live in.
    end = data["coopPlayer2"] + data["sizeofCoopPlayer2"]
    if end > data["sizeofSaveBlock1"]:
        print(
            f"error: coopPlayer2 ends at {end}, past SaveBlock1's "
            f"{data['sizeofSaveBlock1']} bytes.",
            file=sys.stderr,
        )
        return 1

    data["_comment"] = "Generated by tools/coop/emit_offsets.py. Do not edit."
    out.parent.mkdir(parents=True, exist_ok=True)
    with open(out, "w") as fh:
        json.dump(data, fh, indent=2, sort_keys=True)
        fh.write("\n")

    print(f"wrote {out}: coopPlayer2 at {data['coopPlayer2']}, "
          f"{data['sizeofCoopPlayer2']} bytes")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
